# Generated by Django 4.2.1 on 2023-11-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_app', '0002_alter_place_options_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='first_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='full_description',
        ),
    ]
