# Generated by Django 4.2.1 on 2023-11-20 21:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_app', '0003_rename_description_short_place_first_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='first_description',
            field=models.TextField(blank=True, verbose_name='Описание (первый абзац)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='full_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Подробное описание'),
        ),
    ]
