# Generated by Django 4.2.1 on 2023-11-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go_app', '0005_alter_placeimage_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок описания'),
        ),
    ]
